// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pinventory.Pins.Infrastructure;

#nullable disable

namespace Pinventory.MigrationService.Migrations.Pins
{
    [DbContext(typeof(PinsDbContext))]
    partial class PinsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pins")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pinventory.Pins.Domain.Importing.Import", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveJobId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Conflicts")
                        .HasColumnType("integer");

                    b.Property<int>("Created")
                        .HasColumnType("integer");

                    b.Property<int>("Failed")
                        .HasColumnType("integer");

                    b.Property<int>("Processed")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Total")
                        .HasColumnType("bigint");

                    b.Property<int>("Updated")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.ComplexProperty<Dictionary<string, object>>("Period", "Pinventory.Pins.Domain.Importing.Import.Period#Period", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PeriodEnd");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PeriodStart");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId", "State")
                        .IsUnique()
                        .HasFilter("\"State\" = 'InProgress'");

                    b.ToTable("Imports", "pins");
                });

            modelBuilder.Entity("Pinventory.Pins.Domain.Places.Pin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StatusUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.ComplexProperty<Dictionary<string, object>>("Address", "Pinventory.Pins.Domain.Places.Pin.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CountryCode");

                            b1.Property<string>("Line")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Address");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Location", "Pinventory.Pins.Domain.Places.Pin.Location#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Longitude");
                        });

                    b.HasKey("Id");

                    b.HasIndex("PlaceId")
                        .IsUnique();

                    b.ToTable("Pins", "pins");
                });

            modelBuilder.Entity("Pinventory.Pins.Domain.Tags.TagCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.ToTable("TagCatalogs", "pins");
                });

            modelBuilder.Entity("Pinventory.Pins.Domain.Importing.Import", b =>
                {
                    b.OwnsMany("Pinventory.Pins.Domain.Importing.ReportedPlace", "ConflictedPlaces", b1 =>
                        {
                            b1.Property<Guid>("ImportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("MapsUrl")
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("AddedDate")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ImportId", "MapsUrl", "AddedDate");

                            b1.ToTable("ImportConflictedPlaces", "pins");

                            b1.WithOwner()
                                .HasForeignKey("ImportId");
                        });

                    b.OwnsMany("Pinventory.Pins.Domain.Importing.ReportedPlace", "FailedPlaces", b1 =>
                        {
                            b1.Property<Guid>("ImportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("MapsUrl")
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("AddedDate")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ImportId", "MapsUrl", "AddedDate");

                            b1.ToTable("ImportFailedPlaces", "pins");

                            b1.WithOwner()
                                .HasForeignKey("ImportId");
                        });

                    b.Navigation("ConflictedPlaces");

                    b.Navigation("FailedPlaces");
                });

            modelBuilder.Entity("Pinventory.Pins.Domain.Places.Pin", b =>
                {
                    b.OwnsMany("Pinventory.Pins.Domain.Tag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("PinId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasColumnType("text");

                            b1.HasKey("PinId", "Value");

                            b1.HasIndex("Value");

                            b1.ToTable("PinTags", "pins");

                            b1.WithOwner()
                                .HasForeignKey("PinId");
                        });

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Pinventory.Pins.Domain.Tags.TagCatalog", b =>
                {
                    b.OwnsMany("Pinventory.Pins.Domain.Tag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("CatalogId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasColumnType("text");

                            b1.HasKey("CatalogId", "Value");

                            b1.HasIndex("Value");

                            b1.ToTable("CatalogTags", "pins");

                            b1.WithOwner()
                                .HasForeignKey("CatalogId");
                        });

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
